<?php

namespace JLP\CoreBundle\Entity;

/**
 * PasserelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasserelleRepository extends \Doctrine\ORM\EntityRepository
{
}
