<?php
namespace JLP\CoreBundle\Services;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-19 at 15:34:48.
 */
class JLPPasserelleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var JLPPasserelle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new JLPPasserelle;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers JLP\CoreBundle\Services\JLPPasserelle::execute
     * @todo   Implement testExecute().
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Services\JLPPasserelle::informations
     * @todo   Implement testInformations().
     */
    public function testInformations()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Services\JLPPasserelle::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
