jlp_passerelle:
    resource: "@JLPPasserelleBundle/Resources/config/routing.yml"
    prefix:   /

jlp_core:
    resource: "@JLPCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
