JLP\CoreBundle\Entity\Admin:
    type: entity
    table: admin
    id:
        adminId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: admin_id
            generator:
                strategy: IDENTITY
    fields:
        adminLogin:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: admin_login
        adminPassword:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: admin_password
    lifecycleCallbacks: {  }
