JLP\CoreBundle\Entity\Agence:
    type: entity
    table: agence
    id:
        agenceId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: agence_id
            generator:
                strategy: IDENTITY
    fields:
        raisonsocialeagence:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: raisonSocialeAgence
        enseigneagence:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        adresseagence:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        codepostalagence:
            type: integer
            nullable: false
            options:
                unsigned: false
        villeagence:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        paysagence:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        telephoneagence:
            type: integer
            nullable: false
            options:
                unsigned: false
        faxagence:
            type: integer
            nullable: false
            options:
                unsigned: false
        emailagence:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        sitewebagence:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
