JLP\CoreBundle\Entity\Annonce:
    type: entity
    table: annonce
    id:
        annonceId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: annonce_id
            generator:
                strategy: IDENTITY
    fields:
        annonceAgenceId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: annonce_agence_id
        annonceNegociateurId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: annonce_negociateur_id
        statusAnnonce:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: status_annonce
        reference:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nummandat:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: numMandat
        typemandat:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: typeMandat
        categorieoffre:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: categorieOffre
        typebien:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: typeBien
        categorie:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        datecreation:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: dateCreation
        datemodification:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: dateModification
        datedebutmandat:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: dateDebutMandat
        dateecheancemandat:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: dateEcheanceMandat
        datedisponibiliteouliberation:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: dateDisponibiliteOuLiberation
        adresse:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        codepostalpublic:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: codePostalPublic
        villepublique:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: villePublique
        villeaafficher:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: villeAAfficher
        pays:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        quartier:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        environnement:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        proximite:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        transports:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        montant:
            type: integer
            nullable: false
            options:
                unsigned: false
        charges:
            type: integer
            nullable: false
            options:
                unsigned: false
        loyer:
            type: integer
            nullable: false
            options:
                unsigned: false
        depotgarantie:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: depotGarantie
        fraisdivers:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fraisDivers
        loyergarage:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: loyerGarage
        agetete:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: ageTete
        typerente:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: typeRente
        taxehabitation:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: taxeHabitation
        taxefonciere:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: taxeFonciere
        fraisdenotairereduits:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: fraisDeNotaireReduits
        pieces:
            type: integer
            nullable: false
            options:
                unsigned: false
        chambres:
            type: integer
            nullable: false
            options:
                unsigned: false
        sdb:
            type: integer
            nullable: false
            options:
                unsigned: false
        nbsallesdeau:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nbSallesDEau
        nbwc:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nbWC
        nbparking:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nbParking
        nbgarages:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nbGarages
        niveaux:
            type: integer
            nullable: false
            options:
                unsigned: false
        nbetages:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nbEtages
        etage:
            type: integer
            nullable: false
            options:
                unsigned: false
        surface:
            type: integer
            nullable: false
            options:
                unsigned: false
        surfacecarrezouhabitable:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: surfaceCarrezOuHabitable
        surfaceterrain:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: surfaceTerrain
        surfacesejour:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: surfaceSejour
        surfaceterrasse:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: surfaceTerrasse
        surfacebalcon:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: surfaceBalcon
        acceshandicape:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: accesHandicape
        alarme:
            type: integer
            nullable: false
            options:
                unsigned: false
        ascenseur:
            type: integer
            nullable: false
            options:
                unsigned: false
        balcon:
            type: integer
            nullable: false
            options:
                unsigned: false
        bureau:
            type: integer
            nullable: false
            options:
                unsigned: false
        cave:
            type: integer
            nullable: false
            options:
                unsigned: false
        cellier:
            type: integer
            nullable: false
            options:
                unsigned: false
        dependances:
            type: integer
            nullable: false
            options:
                unsigned: false
        dressing:
            type: integer
            nullable: false
            options:
                unsigned: false
        gardien:
            type: integer
            nullable: false
            options:
                unsigned: false
        interphone:
            type: integer
            nullable: false
            options:
                unsigned: false
        lotissement:
            type: integer
            nullable: false
            options:
                unsigned: false
        meuble:
            type: integer
            nullable: false
            options:
                unsigned: false
        mitoyenne:
            type: integer
            nullable: false
            options:
                unsigned: false
        piscine:
            type: integer
            nullable: false
            options:
                unsigned: false
        terrasse:
            type: integer
            nullable: false
            options:
                unsigned: false
        anciennete:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        anneeconstruction:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: anneeConstruction
        exposition:
            type: integer
            nullable: false
            options:
                unsigned: false
        typechauffage:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: typeChauffage
        naturechauffage:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: natureChauffage
        modechauffage:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: modeChauffage
        typecuisine:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: typeCuisine
        coupdecoeur:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: coupDeCoeur
        texte:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        textanglais:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: textAnglais
        urlvisitevirtuelle:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: urlVisiteVirtuelle
        photocoeur:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: photoCoeur
        photomedium:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: photoMedium
        listephotoorig:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: listePhotoOrig
        photothumb:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: photoThumb
        photoorigmd:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: photoOrigMd
        consommationenergie:
            type: integer
            nullable: false
            options:
                unsigned: false
        emissionges:
            type: integer
            nullable: false
            options:
                unsigned: false
        photoorigmd5:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
