JLP\CoreBundle\Entity\Diapointro:
    type: entity
    table: diapointro
    id:
        diapoId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: diapo_id
            generator:
                strategy: IDENTITY
    fields:
        diapoFile:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: diapo_file
    lifecycleCallbacks: {  }
