JLP\CoreBundle\Entity\Passerelle:
    type: entity
    table: passerelle
    id:
        passerelleId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: passerelle_id
            generator:
                strategy: IDENTITY
    fields:
        passerelleDate:
            type: date
            nullable: false
            column: passerelle_date
        passerelleLog:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: passerelle_log
        passerelleNbannonceajouter:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: passerelle_nbannonceajouter
        passerelleNbannoncesuppr:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: passerelle_nbannoncesuppr
        passerelleNbphotomaj:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: passerelle_nbphotomaj
        passerelleNbannoncetraite:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: passerelle_nbannoncetraite
        passerelleStatut:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: passerelle_statut
    lifecycleCallbacks: {  }
