<?php
namespace JLP\CoreBundle\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-19 at 15:36:06.
 */
class AnnonceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Annonce
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Annonce;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setReference
     * @todo   Implement testSetReference().
     */
    public function testSetReference()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getReference
     * @todo   Implement testGetReference().
     */
    public function testGetReference()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setNumMandat
     * @todo   Implement testSetNumMandat().
     */
    public function testSetNumMandat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getNumMandat
     * @todo   Implement testGetNumMandat().
     */
    public function testGetNumMandat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setTypeMandat
     * @todo   Implement testSetTypeMandat().
     */
    public function testSetTypeMandat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getTypeMandat
     * @todo   Implement testGetTypeMandat().
     */
    public function testGetTypeMandat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setCategorieOffre
     * @todo   Implement testSetCategorieOffre().
     */
    public function testSetCategorieOffre()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getCategorieOffre
     * @todo   Implement testGetCategorieOffre().
     */
    public function testGetCategorieOffre()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setCategorie
     * @todo   Implement testSetCategorie().
     */
    public function testSetCategorie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getCategorie
     * @todo   Implement testGetCategorie().
     */
    public function testGetCategorie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setDateCreation
     * @todo   Implement testSetDateCreation().
     */
    public function testSetDateCreation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getDateCreation
     * @todo   Implement testGetDateCreation().
     */
    public function testGetDateCreation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setDateModification
     * @todo   Implement testSetDateModification().
     */
    public function testSetDateModification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getDateModification
     * @todo   Implement testGetDateModification().
     */
    public function testGetDateModification()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setDateDebutMandat
     * @todo   Implement testSetDateDebutMandat().
     */
    public function testSetDateDebutMandat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getDateDebutMandat
     * @todo   Implement testGetDateDebutMandat().
     */
    public function testGetDateDebutMandat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setDateEcheanceMandat
     * @todo   Implement testSetDateEcheanceMandat().
     */
    public function testSetDateEcheanceMandat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getDateEcheanceMandat
     * @todo   Implement testGetDateEcheanceMandat().
     */
    public function testGetDateEcheanceMandat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setDateDisponibiliteOuLiberation
     * @todo   Implement testSetDateDisponibiliteOuLiberation().
     */
    public function testSetDateDisponibiliteOuLiberation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getDateDisponibiliteOuLiberation
     * @todo   Implement testGetDateDisponibiliteOuLiberation().
     */
    public function testGetDateDisponibiliteOuLiberation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setAdresse
     * @todo   Implement testSetAdresse().
     */
    public function testSetAdresse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getAdresse
     * @todo   Implement testGetAdresse().
     */
    public function testGetAdresse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setCodePostalPublic
     * @todo   Implement testSetCodePostalPublic().
     */
    public function testSetCodePostalPublic()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getCodePostalPublic
     * @todo   Implement testGetCodePostalPublic().
     */
    public function testGetCodePostalPublic()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setVillePublique
     * @todo   Implement testSetVillePublique().
     */
    public function testSetVillePublique()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getVillePublique
     * @todo   Implement testGetVillePublique().
     */
    public function testGetVillePublique()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setVilleAAfficher
     * @todo   Implement testSetVilleAAfficher().
     */
    public function testSetVilleAAfficher()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getVilleAAfficher
     * @todo   Implement testGetVilleAAfficher().
     */
    public function testGetVilleAAfficher()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setPays
     * @todo   Implement testSetPays().
     */
    public function testSetPays()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getPays
     * @todo   Implement testGetPays().
     */
    public function testGetPays()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setQuartier
     * @todo   Implement testSetQuartier().
     */
    public function testSetQuartier()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getQuartier
     * @todo   Implement testGetQuartier().
     */
    public function testGetQuartier()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setEnvironnement
     * @todo   Implement testSetEnvironnement().
     */
    public function testSetEnvironnement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getEnvironnement
     * @todo   Implement testGetEnvironnement().
     */
    public function testGetEnvironnement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setProximite
     * @todo   Implement testSetProximite().
     */
    public function testSetProximite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getProximite
     * @todo   Implement testGetProximite().
     */
    public function testGetProximite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setTransports
     * @todo   Implement testSetTransports().
     */
    public function testSetTransports()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getTransports
     * @todo   Implement testGetTransports().
     */
    public function testGetTransports()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setMontant
     * @todo   Implement testSetMontant().
     */
    public function testSetMontant()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getMontant
     * @todo   Implement testGetMontant().
     */
    public function testGetMontant()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setCharges
     * @todo   Implement testSetCharges().
     */
    public function testSetCharges()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getCharges
     * @todo   Implement testGetCharges().
     */
    public function testGetCharges()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setLoyer
     * @todo   Implement testSetLoyer().
     */
    public function testSetLoyer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getLoyer
     * @todo   Implement testGetLoyer().
     */
    public function testGetLoyer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setDepotGarantie
     * @todo   Implement testSetDepotGarantie().
     */
    public function testSetDepotGarantie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getDepotGarantie
     * @todo   Implement testGetDepotGarantie().
     */
    public function testGetDepotGarantie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setFraisDivers
     * @todo   Implement testSetFraisDivers().
     */
    public function testSetFraisDivers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getFraisDivers
     * @todo   Implement testGetFraisDivers().
     */
    public function testGetFraisDivers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setLoyerGarage
     * @todo   Implement testSetLoyerGarage().
     */
    public function testSetLoyerGarage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getLoyerGarage
     * @todo   Implement testGetLoyerGarage().
     */
    public function testGetLoyerGarage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setAgeTete
     * @todo   Implement testSetAgeTete().
     */
    public function testSetAgeTete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getAgeTete
     * @todo   Implement testGetAgeTete().
     */
    public function testGetAgeTete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setTypeRente
     * @todo   Implement testSetTypeRente().
     */
    public function testSetTypeRente()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getTypeRente
     * @todo   Implement testGetTypeRente().
     */
    public function testGetTypeRente()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setTaxeHabitation
     * @todo   Implement testSetTaxeHabitation().
     */
    public function testSetTaxeHabitation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getTaxeHabitation
     * @todo   Implement testGetTaxeHabitation().
     */
    public function testGetTaxeHabitation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setTaxeFonciere
     * @todo   Implement testSetTaxeFonciere().
     */
    public function testSetTaxeFonciere()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getTaxeFonciere
     * @todo   Implement testGetTaxeFonciere().
     */
    public function testGetTaxeFonciere()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setFraisDeNotaireReduits
     * @todo   Implement testSetFraisDeNotaireReduits().
     */
    public function testSetFraisDeNotaireReduits()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getFraisDeNotaireReduits
     * @todo   Implement testGetFraisDeNotaireReduits().
     */
    public function testGetFraisDeNotaireReduits()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setPieces
     * @todo   Implement testSetPieces().
     */
    public function testSetPieces()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getPieces
     * @todo   Implement testGetPieces().
     */
    public function testGetPieces()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setChambres
     * @todo   Implement testSetChambres().
     */
    public function testSetChambres()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getChambres
     * @todo   Implement testGetChambres().
     */
    public function testGetChambres()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setSdb
     * @todo   Implement testSetSdb().
     */
    public function testSetSdb()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getSdb
     * @todo   Implement testGetSdb().
     */
    public function testGetSdb()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setNbSallesDEau
     * @todo   Implement testSetNbSallesDEau().
     */
    public function testSetNbSallesDEau()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getNbSallesDEau
     * @todo   Implement testGetNbSallesDEau().
     */
    public function testGetNbSallesDEau()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setNbWc
     * @todo   Implement testSetNbWc().
     */
    public function testSetNbWc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getNbWc
     * @todo   Implement testGetNbWc().
     */
    public function testGetNbWc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setNbParking
     * @todo   Implement testSetNbParking().
     */
    public function testSetNbParking()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getNbParking
     * @todo   Implement testGetNbParking().
     */
    public function testGetNbParking()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setNbGarages
     * @todo   Implement testSetNbGarages().
     */
    public function testSetNbGarages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getNbGarages
     * @todo   Implement testGetNbGarages().
     */
    public function testGetNbGarages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setNiveaux
     * @todo   Implement testSetNiveaux().
     */
    public function testSetNiveaux()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getNiveaux
     * @todo   Implement testGetNiveaux().
     */
    public function testGetNiveaux()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setNbEtages
     * @todo   Implement testSetNbEtages().
     */
    public function testSetNbEtages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getNbEtages
     * @todo   Implement testGetNbEtages().
     */
    public function testGetNbEtages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setEtage
     * @todo   Implement testSetEtage().
     */
    public function testSetEtage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getEtage
     * @todo   Implement testGetEtage().
     */
    public function testGetEtage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setSurface
     * @todo   Implement testSetSurface().
     */
    public function testSetSurface()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getSurface
     * @todo   Implement testGetSurface().
     */
    public function testGetSurface()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setSurfaceCarrezOuHabitable
     * @todo   Implement testSetSurfaceCarrezOuHabitable().
     */
    public function testSetSurfaceCarrezOuHabitable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getSurfaceCarrezOuHabitable
     * @todo   Implement testGetSurfaceCarrezOuHabitable().
     */
    public function testGetSurfaceCarrezOuHabitable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setSurfaceTerrain
     * @todo   Implement testSetSurfaceTerrain().
     */
    public function testSetSurfaceTerrain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getSurfaceTerrain
     * @todo   Implement testGetSurfaceTerrain().
     */
    public function testGetSurfaceTerrain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setSurfaceSejour
     * @todo   Implement testSetSurfaceSejour().
     */
    public function testSetSurfaceSejour()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getSurfaceSejour
     * @todo   Implement testGetSurfaceSejour().
     */
    public function testGetSurfaceSejour()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setSurfaceTerrasse
     * @todo   Implement testSetSurfaceTerrasse().
     */
    public function testSetSurfaceTerrasse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getSurfaceTerrasse
     * @todo   Implement testGetSurfaceTerrasse().
     */
    public function testGetSurfaceTerrasse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setSurfaceBalcon
     * @todo   Implement testSetSurfaceBalcon().
     */
    public function testSetSurfaceBalcon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getSurfaceBalcon
     * @todo   Implement testGetSurfaceBalcon().
     */
    public function testGetSurfaceBalcon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setAccesHandicape
     * @todo   Implement testSetAccesHandicape().
     */
    public function testSetAccesHandicape()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getAccesHandicape
     * @todo   Implement testGetAccesHandicape().
     */
    public function testGetAccesHandicape()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setAlarme
     * @todo   Implement testSetAlarme().
     */
    public function testSetAlarme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getAlarme
     * @todo   Implement testGetAlarme().
     */
    public function testGetAlarme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setAscenseur
     * @todo   Implement testSetAscenseur().
     */
    public function testSetAscenseur()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getAscenseur
     * @todo   Implement testGetAscenseur().
     */
    public function testGetAscenseur()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setBalcon
     * @todo   Implement testSetBalcon().
     */
    public function testSetBalcon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getBalcon
     * @todo   Implement testGetBalcon().
     */
    public function testGetBalcon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setBureau
     * @todo   Implement testSetBureau().
     */
    public function testSetBureau()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getBureau
     * @todo   Implement testGetBureau().
     */
    public function testGetBureau()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setCave
     * @todo   Implement testSetCave().
     */
    public function testSetCave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getCave
     * @todo   Implement testGetCave().
     */
    public function testGetCave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setCellier
     * @todo   Implement testSetCellier().
     */
    public function testSetCellier()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getCellier
     * @todo   Implement testGetCellier().
     */
    public function testGetCellier()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setDependances
     * @todo   Implement testSetDependances().
     */
    public function testSetDependances()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getDependances
     * @todo   Implement testGetDependances().
     */
    public function testGetDependances()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setDressing
     * @todo   Implement testSetDressing().
     */
    public function testSetDressing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getDressing
     * @todo   Implement testGetDressing().
     */
    public function testGetDressing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setGardien
     * @todo   Implement testSetGardien().
     */
    public function testSetGardien()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getGardien
     * @todo   Implement testGetGardien().
     */
    public function testGetGardien()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setInterphone
     * @todo   Implement testSetInterphone().
     */
    public function testSetInterphone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getInterphone
     * @todo   Implement testGetInterphone().
     */
    public function testGetInterphone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setLotissement
     * @todo   Implement testSetLotissement().
     */
    public function testSetLotissement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getLotissement
     * @todo   Implement testGetLotissement().
     */
    public function testGetLotissement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setMeuble
     * @todo   Implement testSetMeuble().
     */
    public function testSetMeuble()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getMeuble
     * @todo   Implement testGetMeuble().
     */
    public function testGetMeuble()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setMitoyenne
     * @todo   Implement testSetMitoyenne().
     */
    public function testSetMitoyenne()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getMitoyenne
     * @todo   Implement testGetMitoyenne().
     */
    public function testGetMitoyenne()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setPiscine
     * @todo   Implement testSetPiscine().
     */
    public function testSetPiscine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getPiscine
     * @todo   Implement testGetPiscine().
     */
    public function testGetPiscine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setTerrasse
     * @todo   Implement testSetTerrasse().
     */
    public function testSetTerrasse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getTerrasse
     * @todo   Implement testGetTerrasse().
     */
    public function testGetTerrasse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setAnciennete
     * @todo   Implement testSetAnciennete().
     */
    public function testSetAnciennete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getAnciennete
     * @todo   Implement testGetAnciennete().
     */
    public function testGetAnciennete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setAnneeConstruction
     * @todo   Implement testSetAnneeConstruction().
     */
    public function testSetAnneeConstruction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getAnneeConstruction
     * @todo   Implement testGetAnneeConstruction().
     */
    public function testGetAnneeConstruction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setExposition
     * @todo   Implement testSetExposition().
     */
    public function testSetExposition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getExposition
     * @todo   Implement testGetExposition().
     */
    public function testGetExposition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setTypeChauffage
     * @todo   Implement testSetTypeChauffage().
     */
    public function testSetTypeChauffage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getTypeChauffage
     * @todo   Implement testGetTypeChauffage().
     */
    public function testGetTypeChauffage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setNatureChauffage
     * @todo   Implement testSetNatureChauffage().
     */
    public function testSetNatureChauffage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getNatureChauffage
     * @todo   Implement testGetNatureChauffage().
     */
    public function testGetNatureChauffage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setModeChauffage
     * @todo   Implement testSetModeChauffage().
     */
    public function testSetModeChauffage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getModeChauffage
     * @todo   Implement testGetModeChauffage().
     */
    public function testGetModeChauffage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setTypeCuisine
     * @todo   Implement testSetTypeCuisine().
     */
    public function testSetTypeCuisine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getTypeCuisine
     * @todo   Implement testGetTypeCuisine().
     */
    public function testGetTypeCuisine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setCoupDeCoeur
     * @todo   Implement testSetCoupDeCoeur().
     */
    public function testSetCoupDeCoeur()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getCoupDeCoeur
     * @todo   Implement testGetCoupDeCoeur().
     */
    public function testGetCoupDeCoeur()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setTexte
     * @todo   Implement testSetTexte().
     */
    public function testSetTexte()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getTexte
     * @todo   Implement testGetTexte().
     */
    public function testGetTexte()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setTextAnglais
     * @todo   Implement testSetTextAnglais().
     */
    public function testSetTextAnglais()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getTextAnglais
     * @todo   Implement testGetTextAnglais().
     */
    public function testGetTextAnglais()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setUrlVisiteVirtuelle
     * @todo   Implement testSetUrlVisiteVirtuelle().
     */
    public function testSetUrlVisiteVirtuelle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getUrlVisiteVirtuelle
     * @todo   Implement testGetUrlVisiteVirtuelle().
     */
    public function testGetUrlVisiteVirtuelle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setConsommationEnergie
     * @todo   Implement testSetConsommationEnergie().
     */
    public function testSetConsommationEnergie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getConsommationEnergie
     * @todo   Implement testGetConsommationEnergie().
     */
    public function testGetConsommationEnergie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setEmissionGes
     * @todo   Implement testSetEmissionGes().
     */
    public function testSetEmissionGes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getEmissionGes
     * @todo   Implement testGetEmissionGes().
     */
    public function testGetEmissionGes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setAgence
     * @todo   Implement testSetAgence().
     */
    public function testSetAgence()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getAgence
     * @todo   Implement testGetAgence().
     */
    public function testGetAgence()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setNegociateur
     * @todo   Implement testSetNegociateur().
     */
    public function testSetNegociateur()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getNegociateur
     * @todo   Implement testGetNegociateur().
     */
    public function testGetNegociateur()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setProgrammeNeuf
     * @todo   Implement testSetProgrammeNeuf().
     */
    public function testSetProgrammeNeuf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getProgrammeNeuf
     * @todo   Implement testGetProgrammeNeuf().
     */
    public function testGetProgrammeNeuf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::addStatusAnnonce
     * @todo   Implement testAddStatusAnnonce().
     */
    public function testAddStatusAnnonce()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::removeStatusAnnonce
     * @todo   Implement testRemoveStatusAnnonce().
     */
    public function testRemoveStatusAnnonce()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getStatusAnnonce
     * @todo   Implement testGetStatusAnnonce().
     */
    public function testGetStatusAnnonce()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::addTypeBien
     * @todo   Implement testAddTypeBien().
     */
    public function testAddTypeBien()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::removeTypeBien
     * @todo   Implement testRemoveTypeBien().
     */
    public function testRemoveTypeBien()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::getTypeBien
     * @todo   Implement testGetTypeBien().
     */
    public function testGetTypeBien()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setStatusAnnonce
     * @todo   Implement testSetStatusAnnonce().
     */
    public function testSetStatusAnnonce()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::addTypeMandat
     * @todo   Implement testAddTypeMandat().
     */
    public function testAddTypeMandat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::removeTypeMandat
     * @todo   Implement testRemoveTypeMandat().
     */
    public function testRemoveTypeMandat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JLP\CoreBundle\Entity\Annonce::setTypeBien
     * @todo   Implement testSetTypeBien().
     */
    public function testSetTypeBien()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
