<?php

namespace JLP\CoreBundleBundle\Entity;

/**
 * SiteConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
