<?php

namespace JLP\CoreBundleBundle\Entity;

/**
 * StatusAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
