<?php

namespace JLP\CoreBundleBundle\Entity;

/**
 * TypeBienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeBienRepository extends \Doctrine\ORM\EntityRepository
{
}
