<?php

namespace JLP\CoreBundleBundle\Entity;

/**
 * TypeMandatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMandatRepository extends \Doctrine\ORM\EntityRepository
{
}
