services:
    jlp_core.passerelle:
        class: JLP\CoreBundle\Services\JLPPasserelle
        arguments: [@kernel,"debug","%jlp_core.passerelle.zip_name%"]
    
    jlp_core.parser.agence:
        class: JLP\CoreBundle\Services\JLPAgenceParser
        arguments: [@kernel,@doctrine.orm.entity_manager]
    
    jlp_core.exporter:
        class: JLP\CoreBundle\Services\JLPExporter
        arguments: [@kernel,@doctrine.orm.entity_manager]