parameters:
    passerelle.class: JLP\CoreBundle\Service\Passerelle
    passerelle.yaml_config_file: "%kernel.root_dir%/../src/JLP/CoreBundle/Resources/config/%passerelle_logiciel_name%.yml"

services:
    jlp_core.passerelle:
        class: JLP\CoreBundle\Services\JLPPasserelle
        arguments: [@kernel,%passerelle.yaml_config_file%,@doctrine.orm.entity_manager,@jlp_core.parser,"debug"]
    
    jlp_core.parser:
        class: JLP\CoreBundle\Services\JLPParser
        arguments: [@kernel,@doctrine.orm.entity_manager,@logger,%passerelle.yaml_config_file%]
    
    jlp_core.image_tool:
        class: JLP\CoreBundle\EventListener\ImagesToolsSubscriber
        arguments:
            logger: "@logger"
        tags:
            - { name: doctrine.event_subscriber }

