services:
    jlp_core.passerelle:
        class: JLP\CoreBundle\Services\JLPPasserelle
        arguments: [@kernel,"debug"]
    
    jlp_core.agence_parser:
        class: JLP\CoreBundle\Services\JLPAgenceParser
        arguments: [@kernel,@doctrine.orm.entity_manager]
