<?php

namespace JLP\CoreBundle\Repository;

/**
 * AgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceRepository extends \Doctrine\ORM\EntityRepository
{
  
    public function getAgenceWithoutNegociateur()
    {

    $qb = $this->createQueryBuilder('ag')
            ->leftJoin('ag.negociateurs', 'n')
            ->where('n.id is null');
      
    $aResult = $qb->getQuery()->getResult();
    
    return $aResult;
    }
  
}
