<?php

namespace JLP\CoreBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
  
    public function getCoupsDeCoeurs()
    {
    $oQb = $this
        ->createQueryBuilder('a')
        ->innerJoin('a.typeBien','tbbien')
        ->innerJoin('a.typeMandat', 'tmandat')
        ->leftJoin('a.images', 'img')
        ->addSelect('tbbien')   
        ->addSelect('tmandat')  
        ->addSelect('img')
        ->where('a.coupDeCoeur',true)
        ;

        return $oQb
        ->getQuery()
        ->getResult()
        ;
    }

}
