<?php

namespace JLP\CoreBundle\Repository;

/**
 * NegociateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NegociateurRepository extends \Doctrine\ORM\EntityRepository
{
}
