<?php

namespace JLP\CoreBundle\Entity;

/**
 * ProgrammeNeufRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammeNeufRepository extends \Doctrine\ORM\EntityRepository
{
}
